<h1> Практика матриц </h1>

Создать класс <b>"Матрица"</b>, в котором хранятся матрицы и операции над ними по типу \_\_add__, \_\_mult__.<br>
Нужны: +, -, *, /, @ (Скалярное произведение), len, T (Транспонирование), ==, repr

In [1]:
class Matrix:

    def __init__(
        self, 
        matrix: list[list[int]], 
        rows: int = None, 
        cols: int = None
        ):
        self.matrix = matrix
        if rows is None:           # FIX THIS!
            self.rows = len(matrix)
        else:
            self.rows = rows
        if cols is None:
            self.cols = len(matrix[0])        
        else:
            self.cols = cols

    def T(self):
        tr_matrix = [[0 for j in range(self.rows)] for i in range(self.cols)]
        for i in range(self.cols):
            for j in range(self.rows):
                tr_matrix[i][j] = self.matrix[j][i]
        # return tr_matrix
        return Matrix(tr_matrix, len(tr_matrix), len(tr_matrix[0]))

        # tr_matrix = []
        # for i in range(self.cols):
        #     temp = []
        #     for j in range(self.rows):
        #         temp.append(self.matrix[j][i])
        #     tr_matrix.append(temp)
        # return tr_matrix

    def __len__(self):
        return self.rows * self.cols

    def __add__(self, other):
        if isinstance(other, Matrix):
            if self.rows == other.rows and self.cols == other.cols:
                res_matrix = []
                for i in range(self.rows):
                    temp = []
                    for j in range(self.cols):
                        temp.append(self.matrix[i][j] + other.matrix[i][j])
                    res_matrix.append(temp)
                return res_matrix
            else:
                return "Невозможно сложить матрицы разных размеров!"
        elif (other, (int, float)):
            res_matrix = []
            for i in range(self.rows):
                temp = []
                for j in range(self.cols):
                    temp.append(self.matrix[i][j] + other)
                res_matrix.append(temp)
            return res_matrix            
    
    def __sub__(self, other):
        if isinstance(other, Matrix):
            if self.rows == other.rows and self.cols == other.cols:
                res_matrix = []
                for i in range(self.rows):
                    temp = []
                    for j in range(self.cols):
                        temp.append(self.matrix[i][j] - other.matrix[i][j])
                    res_matrix.append(temp)
                return res_matrix
            else:
                return "Невозможно вычесть матрицы разных размеров!"
        elif (other, (int, float)):
            res_matrix = []
            for i in range(self.rows):
                temp = []
                for j in range(self.cols):
                    temp.append(self.matrix[i][j] - other)
                res_matrix.append(temp)
            return res_matrix            

    def __mul__(self, other):                   # Умножает соразмерные матрицы в порядке: a[i][j] * b[i][j]
        if isinstance(other, Matrix):
            if self.cols == other.cols and self.rows == other.rows:
                res_matrix = [[0 for i in range(self.cols)] for j in range(self.rows)]
                for i in range(self.rows):
                    for j in range(self.cols):
                        res_matrix[i][j] = self.matrix[i][j] * other.matrix[i][j]
                return res_matrix
            else:
                return "Невозможно умножить несоразмерные матрицы!"
        elif isinstance(other, (int, float)):
            res_matrix = []
            for i in range(self.rows):
                temp = []
                for j in range(self.cols):
                    temp.append(self.matrix[i][j] * other)
                res_matrix.append(temp)
            return res_matrix

    def __truediv__(self, other):               # Делит соразмерные матрицы в порядке: a[i][j] / b[i][j]
        if isinstance(other, Matrix):
            if self.cols == other.cols and self.rows == other.rows:
                res_matrix = [[0 for i in range(self.cols)] for j in range(self.rows)]
                for i in range(self.rows):
                    for j in range(self.cols):
                        res_matrix[i][j] = self.matrix[i][j] / other.matrix[i][j]
                return res_matrix
            else:
                return "Невозможно разделить несоразмерные матрицы!"
        elif isinstance(other, (int, float)):
            res_matrix = [[0 for i in range(self.cols)] for j in range(self.rows)]
            for i in range(self.rows):
                for j in range(self.cols):
                    res_matrix[i][j] = self.matrix[i][j] / other
            return res_matrix

    def __matmul__(self, other):                    # А вот это уже и есть умножение матриц!
        if isinstance(other, Matrix):
            if self.cols == other.rows:
                res_matrix = [[0 for i in range(other.cols)] for j in range(self.rows)]
                for i in range(self.rows):
                    for j in range(other.cols):
                        for k in range(self.cols):
                            res_matrix[i][j] += self.matrix[i][k] * other.matrix[k][j]
                return res_matrix
            else:
                return "Невозможно умножить матрицы, если количество колонок в первой не соответствует количеству рядов во второй!"
        elif isinstance(other, list):
            # mother = Matrix(other, len(other), len(other[0]))
            if self.cols == len(other):
                res_matrix = [[0 for i in range(len(other[0]))] for j in range(self.rows)]
                for i in range(self.rows):
                    for j in range(len(other[0])):
                        for k in range(self.cols):
                            res_matrix[i][j] += self.matrix[i][k] * other[k][j]
                return res_matrix
            else:
                return "Невозможно умножить матрицы, если количество колонок в первой не соответствует количеству рядов во второй!"

    def __eq__(self, other):
        if isinstance(other, Matrix):
            if self.rows == other.rows and self.cols == other.cols:
                for i in range(self.rows):
                    for j in range(other.cols):
                        if self.matrix[j][i] != other.matrix[j][i]:
                            return False
                return True
            else:
                return False
        elif isinstance(other, list[list[int]]):
            if self.rows == len(other) and self.cols == len(other[0]):
                for i in range(self.rows):
                    for j in range(self.cols):
                        if self.matrix[i][j] != other[i][j]:
                            return False
                return True
            else:
                return False
    
    def __repr__(self):
        out = ["array([", str(self.matrix[0])]
        if self.rows > 1:
            for i in range(1, self.rows):
                out.append(",\n")
                out.append("        ")
                out.append(str(self.matrix[i]))
        out.append("])")
        return "".join(out)



In [2]:
%pip install -Uq numpy
%pip install -q ipytest pytest

import numpy as np
import ipytest
import pytest
ipytest.autoconfig()

Note: you may need to restart the kernel to use updated packages.
Note: you may need to restart the kernel to use updated packages.


In [3]:
%%ipytest

matrix1, matrix2 = Matrix([[1, 1, 1], [1, 2, 3], [11, 12, 13], [11, 22, 33]]), Matrix([[4, 5, 6], [7, 8, 9], [77, 12, 12], [2, 1, 45]], 4, 3)

@pytest.mark.parametrize("matrix1,matrix2", [[matrix1, matrix2]])
def test_matrix_add_matrix(matrix1: Matrix, matrix2: Matrix):
    assert (
        (matrix1 + matrix2 == (np.array(matrix1.matrix) + np.array(matrix2.matrix))).all()
    ), 'add section with matrices is not working right'

@pytest.mark.parametrize("matrix1,number", [[matrix1, 13.2]])
def test_matrix_add_number(matrix1: Matrix, number: int | float):
    assert (
        (matrix1 + number == np.array(matrix1.matrix) + number).all()
    ), 'add section with matrix and number is not working right'

@pytest.mark.parametrize("matrix1,matrix2", [[matrix1, matrix2]])
def test_matrix_sub_matrix(matrix1: Matrix, matrix2: Matrix):
    assert (
        (matrix1 - matrix2 == np.array(matrix1.matrix) - np.array(matrix2.matrix)).all()
    ), 'sub section with matrices is not working right'

@pytest.mark.parametrize("matrix1,number", [[matrix1, 12.2]])    
def test_matrix_sub_number(matrix1: Matrix, number: int | float):
    assert (
        (matrix1 - number == np.array(matrix1.matrix) - number).all()
    ), 'sub section with matrix and number is not working right'

@pytest.mark.parametrize("matrix1", [matrix1])    
def test_matrix_transpose(matrix1: Matrix):
    assert (
        (matrix1.T().matrix == np.array(matrix1.matrix).T).all()
    ), 'transpose section is not working right'
    
# -----------------------------------------

@pytest.mark.parametrize("matrix1,matrix2", [[matrix1, matrix2]])
def test_matrix_mul_matrix(matrix1: Matrix, matrix2: Matrix):
    assert (
        (matrix1 * matrix2 == np.array(matrix1.matrix) * np.array(matrix2.matrix)).all()
    ), 'mul section with matrices is not working right'

@pytest.mark.parametrize("matrix1,number", [[matrix1, 13]])
def test_matrix_mul_number(matrix1: Matrix, number: int | float):
    assert (
        (matrix1 * number == np.array(matrix1.matrix) * number).all()
    ), 'mul section with matrix and number is not working right'

@pytest.mark.parametrize("matrix1,matrix2", [[matrix1, matrix2]])    
def test_matrix_div_matrix(matrix1: Matrix, matrix2: Matrix):
    assert (
        (matrix1 / matrix2 == np.array(matrix1.matrix) / np.array(matrix2.matrix)).all()
    ), 'div section with matrices is not working right'

@pytest.mark.parametrize("matrix1,number", [[matrix1, 2]])    
def test_matrix_div_number(matrix1: Matrix, number: int | float):
    assert (
        (matrix1 / number == np.array(matrix1.matrix) / number).all()
    ), 'div section with matrix and number is not working right'

@pytest.mark.parametrize("matrix1,matrix2", [[matrix1, matrix2.T()]])    
def test_matrix_matmul_matrix(matrix1: Matrix, matrix2: Matrix):
    assert(
        (matrix1 @ matrix2 == np.array(matrix1.matrix) @ np.array(matrix2.matrix)).all()
    ), 'matmul section is not working right, and don\'t forget about T() if needed'
    
    

..........                                                                                   [100%]
10 passed in 0.04s


<h2>Далее идут мои тесты</h2>

In [22]:
matrix1, matrix2 = Matrix([[1, 2],[3, 4]], 2, 2), Matrix([[5, 6],[7, 8]], 2, 2)
matrix3, matrix4 = Matrix([[i for i in range(j, j+4)] for j in range(4)]), Matrix([[i for i in range(j, j+4)] for j in range(1, 5)])
matrix5, matrix6 = Matrix([[1, 2, 3]], 1, 3), Matrix([[4], [5], [6]], 3, 1)
matrix7, matrix8 = Matrix([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]], 3, 4), Matrix([[12, 11, 10], [9, 8, 7], [6, 5, 4], [3, 2, 1]], 4, 3)

In [23]:
print(matrix1 + matrix2)

[[6, 8], [10, 12]]


In [24]:
matrix_sum = matrix1 + matrix2
print(f"{matrix1.matrix}\nприбавить \n{matrix2.matrix}\nравно\n{matrix_sum}\n")

matrix_sub = matrix1 - matrix2
print(f"{matrix1.matrix}\nвычесть \n{matrix2.matrix}\nравно\n{matrix_sub}\n")

[[1, 2], [3, 4]]
прибавить 
[[5, 6], [7, 8]]
равно
[[6, 8], [10, 12]]

[[1, 2], [3, 4]]
вычесть 
[[5, 6], [7, 8]]
равно
[[-4, -4], [-4, -4]]



In [25]:
print(f"Lengths: \nMatrix 1: {len(matrix1)}\nMatrix 2: {len(matrix2)}\nMatrix 6: {len(matrix6)}\nMatrix 7: {len(matrix7)}")

Lengths: 
Matrix 1: 4
Matrix 2: 4
Matrix 6: 3
Matrix 7: 12


In [26]:
matrix1 == matrix2

False

In [27]:
matrix1_1 = Matrix([[1, 2],[3, 4]], 2, 2)

matrix1 == matrix1_1

True

In [28]:
matrix1 == matrix6

False

In [29]:
matrix6 * matrix1

'Невозможно умножить несоразмерные матрицы!'

In [30]:
matrix6 * matrix5

'Невозможно умножить несоразмерные матрицы!'

In [31]:
print(matrix6 @ matrix5)
print(np.array(matrix6.matrix) @ np.array(matrix5.matrix))

[[4, 8, 12], [5, 10, 15], [6, 12, 18]]
[[ 4  8 12]
 [ 5 10 15]
 [ 6 12 18]]


In [32]:
print(matrix1 @ matrix2)
print(np.array(matrix1.matrix) @ np.array(matrix2.matrix))

[[19, 22], [43, 50]]
[[19 22]
 [43 50]]


In [33]:
print(matrix3 * matrix4)
print()
print(np.array(matrix3.matrix) * np.array(matrix4.matrix))

[[0, 2, 6, 12], [2, 6, 12, 20], [6, 12, 20, 30], [12, 20, 30, 42]]

[[ 0  2  6 12]
 [ 2  6 12 20]
 [ 6 12 20 30]
 [12 20 30 42]]


In [34]:
print(matrix3 / matrix4)
print()
print(np.array(matrix3.matrix) / np.array(matrix4.matrix))

[[0.0, 0.5, 0.6666666666666666, 0.75], [0.5, 0.6666666666666666, 0.75, 0.8], [0.6666666666666666, 0.75, 0.8, 0.8333333333333334], [0.75, 0.8, 0.8333333333333334, 0.8571428571428571]]

[[0.         0.5        0.66666667 0.75      ]
 [0.5        0.66666667 0.75       0.8       ]
 [0.66666667 0.75       0.8        0.83333333]
 [0.75       0.8        0.83333333 0.85714286]]


In [35]:
repr(matrix4)

'array([[1, 2, 3, 4],\n        [2, 3, 4, 5],\n        [3, 4, 5, 6],\n        [4, 5, 6, 7]])'

In [36]:
repr(np.array(matrix4.matrix))

'array([[1, 2, 3, 4],\n       [2, 3, 4, 5],\n       [3, 4, 5, 6],\n       [4, 5, 6, 7]])'

In [37]:
print(matrix5.matrix, matrix5.T().matrix, np.array(matrix5.matrix).T, sep="\n\n")
print()
print(matrix8.matrix, matrix8.T().matrix, np.array(matrix8.matrix).T, sep="\n\n")
print()
print(matrix2.matrix, matrix2.T().matrix, np.array(matrix2.matrix).T, sep="\n\n")

[[1, 2, 3]]

[[1], [2], [3]]

[[1]
 [2]
 [3]]

[[12, 11, 10], [9, 8, 7], [6, 5, 4], [3, 2, 1]]

[[12, 9, 6, 3], [11, 8, 5, 2], [10, 7, 4, 1]]

[[12  9  6  3]
 [11  8  5  2]
 [10  7  4  1]]

[[5, 6], [7, 8]]

[[5, 7], [6, 8]]

[[5 7]
 [6 8]]


In [38]:
print(matrix1 @ matrix2.T())
print()
print(np.array(matrix1.matrix) @ np.array(matrix2.matrix).T)

[[17, 23], [39, 53]]

[[17 23]
 [39 53]]
